name: GitHub Actions test for CI/CD pipelines
author: internetarchive
branding:
  icon: 'globe'
  color: 'white'

inputs:
  TEST_SCRIPT:
    description: 'default looks for test.sh at top of your repo and runs it.  pass in alt pathname'
    default: './test.sh'
    required: false

  # cant make the `image:` below anything but a hardcoded string :(
  # TEST_IMAGE:
  #  description: 'defaults to use your just built docker image.  pass in alt docker image to use'
  #  default: 'docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
  #  required: false

runs:
  # https://github.com/internetarchive/dyno
  image: 'docker://ghcr.io/internetarchive/dyno:main'
  using: 'docker'
  args:
    - 'sh'
    - '-ec'
    - 'if [ -e ${{ inputs.TEST_SCRIPT }} ]; then ${{ inputs.TEST_SCRIPT }}; fi'
