name: GitHub Actions test for CI/CD pipelines
author: internetarchive

inputs:
  TEST_SCRIPT:
    description: 'default looks for [WORKDIR]/test.sh in docker image and runs it.  pass in alt pathname'
    default: './test.sh'
    required: false

  TEST_IMAGE:
    description: 'defaults to use your just built docker image.  pass in alt docker image to use'
    default: 'docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
    required: false

runs:
  # xxxd
  # image: 'docker://ghcr.io/internetarchive/dyno:main'
  image: ${{ inputs.TEST_IMAGE }}
  using: 'docker'
  args:
    - 'sh'
    - '-ec'
    - 'if [ -e ${{ inputs.TEST_SCRIPT }} ]; then ${{ inputs.TEST_SCRIPT }}; fi'
